Select ID_LOCACAO,ID_CLIENTE_LOCACAO,ID_VEICULO_LOCACAO,DT_LOCACAO,DS_KM_RETIRADA, 
		TB_CLIENTE.NM_CLIENTE,TB_CLIENTE.DS_CPF, 
		TB_VEICULO.DS_MODELO,TB_VEICULO.DS_ANO,TB_VEICULO.DS_PLACA
		from TB_LOCACAO
			Inner Join TB_CLIENTE ON TB_LOCACAO.ID_CLIENTE_LOCACAO = TB_CLIENTE.ID_CLIENTE
            Inner Join TB_VEICULO ON TB_LOCACAO.ID_VEICULO_LOCACAO = TB_VEICULO.ID_VEICULO;
#Selecionar todos apenas para auxiliar na API

Select DT_LOCACAO, 
		TB_CLIENTE.NM_CLIENTE,TB_CLIENTE.DS_CPF, 
		TB_VEICULO.DS_MODELO,TB_VEICULO.DS_PLACA
		from TB_LOCACAO
			Inner Join TB_CLIENTE ON TB_LOCACAO.ID_CLIENTE_LOCACAO = TB_CLIENTE.ID_CLIENTE
            Inner Join TB_VEICULO ON TB_LOCACAO.ID_VEICULO_LOCACAO = TB_VEICULO.ID_VEICULO
		WHERE NM_CLIENTE=?
        AND DS_CPF=?;

Delete from TB_LOCACAO
	WHERE ID_LOCACAO=?;